---

name: Super-lint project

on:
  push: {}

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Super-Linter for everything
        uses: github/super-linter@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: yes
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .git/**
